# Generated by Django 3.2.4 on 2021-06-26 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0002_auto_20210625_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subComments', to='fb.comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
